package com.amazonaws.lambda.demo;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.Test;

import com.amazonaws.services.lambda.runtime.Context;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;

/**
 * A simple test harness for locally invoking your Lambda function handler.
 */
public class LambdaFunctionHandlerTest {

    private static Object input;

    @BeforeClass
    public static void createInput() throws IOException {
        // TODO: set up your sample input object here.
        input = null;
    }

    private Context createContext() {
        TestContext ctx = new TestContext();

        // TODO: customize your context here if needed.
        ctx.setFunctionName("Your Function Name");

        return ctx;
    }

    @Test
    public void testLambdaFunctionHandler() throws JsonParseException, JsonMappingException, IOException {
        LambdaFunctionHandler handler = new LambdaFunctionHandler();
        Context ctx = createContext();
//        System.out.println("{"
//    			+ "\"dialogState\": \"Fulfilled\","
//    			+ "\"intentName\": \"RateQuote\","
//    			+ "\"message\":\"Ratequote is Generated by ArchMI's Quote Generator\", "
//    			+ "\"messageFormat\":\"PlainText\" "
//    		+"}");
        
//        System.out.println("{"
//        		+"dialogAction:"
//        		+ "{"
//    			+ "type:Close,"
//    			+ "fulfillmentState:Fulfilled,"
//    			+ "message:"
//    					+ "{"
//    						+ "contentType:PlainText,"
//    						+ "content:Rate Quote Generated Successfully Arch Test AWS Lambda Function."
//    					+"}"
//    			+ "}"
//    			+"}");
        
        String returnstring = "{"
        		
				+ "\"sessionAttributes\": "
				+ "{"
					+ "\"key1\": \"Value1\""
				+ "},"
        		+ "\"dialogAction\": "
        		+ "{"
    			+ "\"type\": \"Close\","
    			+ "\"fulfillmentState\": \"Fulfilled\","
    			+ "\"message\": "
    					+ "{"
    						+ "\"contentType\": \"PlainText\","
    						+ "\"content\": \"Rate Quote Generated Successfully Arch Test AWS Lambda Function.\""
    					+"}"
    			+ "}"
    		+"}";
        
        returnstring = "{messageVersion=1.0, invocationSource=FulfillmentCodeHook, userId=l83mtcmucmt6j7q9kz17r1qgmtds52as, sessionAttributes={}, requestAttributes=null, bot={name=RateQuoteBot, alias=$LATEST, version=$LATEST}, outputDialogMode=Text, currentIntent={name=RateQuote, slots={LoanAmount=780000, PropertyType=SF, CreditScore=780, CoveragePercentage=12, PropertyZipCode=GSO, LTV=85}, slotDetails={LoanAmount={resolutions=[], originalValue=780000}, PropertyType={resolutions=[], originalValue=SF}, CreditScore={resolutions=[], originalValue=780}, CoveragePercentage={resolutions=[], originalValue=12}, PropertyZipCode={resolutions=[], originalValue=GSO}, LTV={resolutions=[], originalValue=85}}, confirmationStatus=None}, inputTranscript=SF}";
		System.out.println(returnstring);
        
        ObjectMapper mapper = new ObjectMapper();
		Map<String, Object> map = new HashMap<String, Object>();
		String reg= returnstring.replaceAll("[^\\{\\},]+", "\"$0\"");
		String returnstringJSON=reg.replace("\"[\"{", "[{").
				replace("=","\":\"").replace(" ","").
				replace("}\"]\"","}]").
				replace(":\"\"{",":{").
				replace("\"true\"", "true").replace("\"false\"", "false");
		
		
		
		System.out.println(returnstringJSON);
		try {
			map = mapper.readValue(returnstringJSON,  new TypeReference<Map<String, Object>>(){});
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		System.out.println("Printing MAP");
		
		if(map!=null){
			Map<String, Object> currentIntentMap = (Map<String,Object>)map.get("currentIntent");
			if(currentIntentMap!=null){
				Map<String,Object> slotsMap = (Map<String, Object>) currentIntentMap.get("slots");
				if(slotsMap!=null){
					System.out.println("LoanAmount"+slotsMap.get("LoanAmount"));
					System.out.println("PropertyType"+slotsMap.get("PropertyType"));
					System.out.println("CreditScore"+slotsMap.get("CreditScore"));
					System.out.println("CoveragePercentage"+slotsMap.get("CoveragePercentage"));
					System.out.println("PropertyZipCode"+slotsMap.get("PropertyZipCode"));
					System.out.println("LTV: "+slotsMap.get("LTV"));
				}
			}
		}
		Object output = handler.handleRequest(input, ctx);
        // TODO: validate output here if needed.
        Assert.assertEquals("Hello from AWS Lambda - Java One Updates at Arch MI !", output);
    }
}
